# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    translator: { fallbacks: ['en'] }
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    default_locale: 'en'
    trusted_hosts: ~
    trusted_proxies: '192.0.0.1,10.0.0.0/8'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    fragments: ~
    http_method_override: true
    assets: ~
