twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: ~
    form_themes: ['template/forms.html.twig']
    globals:
        favourite_service: '@App\Service\FavouriteService'
